### ISSUE TITLE
IOS show low quality images

### ISSUE THREAD

**Issue by xOnlyFadi** [rs1703/koushoku#11] opened 2022-05-16 23:24 UTC
Hey it's me again when going to reader on IOS the on any browser it shows low quality images is this a IOS problem?

**Comment by rs1703** [comment] 2022-05-16 23:42
As far as I know, Safari uses WebKit Engine. Well I already know what's causing this, but just to be safe, can you send me a safe for work (SFW) example/screenshot of the reader in your browser?

**Comment by xOnlyFadi** [comment] 2022-05-17 04:25
![F94A7966-9715-44A4-91D2-53C9A90B9BC2](https://user-images.githubusercontent.com/63213308/168728620-48d6d088-30e2-4c07-b8ef-bc3354602474.jpeg)
![99A8071A-DC38-40C7-B9A6-0341E733CAB4](https://user-images.githubusercontent.com/63213308/168728626-662a8104-9b30-47af-8131-df52f73201ab.jpeg)

**Comment by rs1703** [comment] 2022-05-17 05:39
I have updated the CSS. Please let me know if it's still the same, otherwise you can close this issue, thanks.

**Comment by xOnlyFadi** [comment] 2022-05-17 05:46
If the cache is cleared only the image that loaded is high quality the others are different 
![464CDAA4-3E36-4505-8680-16CAA8DDED9E](https://user-images.githubusercontent.com/63213308/168737851-da86c7dc-7fb8-42c7-81fa-e914a7935cc8.jpeg)
![6B79D004-EB63-45A7-8DE9-7A1EBDAA5A40](https://user-images.githubusercontent.com/63213308/168737858-b30ff811-cd20-4c3e-8181-54737192e11a.jpeg)
![5D8B5FDB-24B1-4CFB-8738-8B75381EA33D](https://user-images.githubusercontent.com/63213308/168737863-609cc309-f4e7-4ef5-87c1-d02195b197de.jpeg)

**Comment by rs1703** [comment] 2022-05-17 06:10
There's nothing wrong with the images itself, the browser just can't render it properly especially when the image is bigger than your screen. When it's trying to render the image in a lower size than its original size, the image would be blurred or being too sharp. Alternative solution would be to just download the archive and read it in your favorite image viewer or manga reader or something like Tachiyomi but for ios. Paperback might be what you want but it seems really meh.

**Comment by xOnlyFadi** [comment] 2022-05-17 06:13
so i should just make a paperback source and read overthere?

**Comment by xOnlyFadi** [comment] 2022-05-17 06:14
> There's nothing wrong with the image itself, the browser just can't render it properly especially when the image is bigger than your screen. When it's trying to render the image in a lower size than its original size, the image would be blurred or being too sharp. Alternative solution would be to just download the archive and read it in your favorite image viewer or manga reader or something like Tachiyomi but for ios. Paperback might be what you want but it seems really meh.

Before the site was updated the images would render in high quality with no problems at all

**Comment by rs1703** [comment] 2022-05-17 06:33
> so i should just make a paperback source and read overthere?

I don't know if they have the extension, and don't know how it works but I can try develop one, or if you know how to make it yourself then I won't stop you.

> Before the site was updated the images would render in high quality with no problems at all

I doubt that's the cause. It probably depend on the original size of the image, for instance, the original height of the images in the related archive is 3200 pixels. You can make sure if this issue also happens on a different archives with different original heights. You can do so by checking these:

- Spring Yearning - 3200 pixels
- Ayaka's Secret - 1920 pixels

**Comment by xOnlyFadi** [comment] 2022-05-17 06:39
> > so i should just make a paperback source and read overthere?
> 
> I don't know if they have the extension, and don't know how it works but I can try develop one, or if you know how to make it yourself then I won't stop you.
> 
Sure i can make one for paperback i have made some sources for the app and this one is gonna be easy for me

**Comment by rs1703** [comment] 2022-05-17 06:50
> Sure i can make one for paperback i have made some sources for the app and this one is gonna be easy for me

Nice thanks, please do so. Here's a reference in case you need it. The icons are also there, it's for Tachiyomi but it should be interoperable since Paperback is written in TypeScript. https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/en/koushoku

**Comment by xOnlyFadi** [comment] 2022-05-17 19:29
> > Sure i can make one for paperback i have made some sources for the app and this one is gonna be easy for me
> 
> Nice thanks, please do so. Here's a reference in case you need it. The icons are also there, it's for Tachiyomi but it should be interoperable since Paperback is written in TypeScript. https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/en/koushoku

And ill make one for mangaxmanga ios it has very similar style to make sources in the js here is one the code for MxM
https://github.com/chubimauk/MangaxMangaOpenSources/blob/main/sources%20for%20users/sources-dev/asurascans/asurascans.js

**Comment by rs1703** [comment] 2022-05-17 22:48
> > > Sure i can make one for paperback i have made some sources for the app and this one is gonna be easy for me
> > 
> > 
> > Nice thanks, please do so. Here's a reference in case you need it. The icons are also there, it's for Tachiyomi but it should be interoperable since Paperback is written in TypeScript. https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/en/koushoku
> 
> And ill make one for mangaxmanga ios it has very similar style to make sources in tachi here is one the codes for MxM source https://github.com/chubimauk/MangaxMangaOpenSources/blob/main/sources%20for%20users/sources-dev/asurascans/asurascans.js

Looks neat, that would be of great help. Fyi, the tachi extension source is a bit outdated (too lazy to update it). Now you don't need to use regex to parse the archive id in the function **_pageListParse_**, instead you can just get it from the dataset attributes (data-id), you can also get the total pages and slug from it.

If you have any questions feel free to let me know.

**Comment by xOnlyFadi** [comment] 2022-05-21 18:13
I have a question are all images on the site jpg or some are png?

**Comment by rs1703** [comment] 2022-05-22 02:46
> I have a question are all images on the site jpg or some are png?

It's dynamic, and different each archive. The file extension in the URL is just a decoration (e.g., cdn.koushoku.org/data/id-of-archive/1.jpg) so that the file will be cached by Cloudflare. By default, the site is using .jpg for all images, but you can use .png, .webp or even without extension because the browser will automatically handle the correct mime type which obtained from the response header instead of the file extension. I encourage you to use .jpg because of caching issues.

**Comment by xOnlyFadi** [comment] 2022-05-22 02:52
> > I have a question are all images on the site jpg or some are png?
> 
> It's dynamic, and different for each archive. The file extension in the URL is just a decoration (e.g., cdn.koushoku.org/data/id-of-archive/1.jpg) so that the file will be cached by Cloudflare. By default, the site is using .jpg for all images, but you can use .png, .webp or even without extension because the browser will automatically handle the correct mime type, which can be obtained from the response header instead of the file extension. I encourage you to use .jpg because of caching issues.

oh ok thanks, and I just finished coding the site for paperback as a source here is the code
https://github.com/xOnlyFadi/h-extensions/tree/main/src/Koushoku

**Comment by rs1703** [comment] 2022-05-22 03:03
Are you sure this is correct? L33 you're iterating arrMonthly but pushing the entry into latest, and L45 section1 is 'Weekly Trending' but you're assigning latest into it. Same as L48 and L60, L63 and L75.

https://github.com/xOnlyFadi/h-extensions/blob/55e74ee12b16cabd6c45ce87b61d84175cb41169/src/Koushoku/KoushokuParser.ts#L33-L76

**Comment by xOnlyFadi** [comment] 2022-05-22 03:10
> Are you sure this is correct? L33 you're iterating arrMonthly but pushing the entry into latest, and L45 section1 is 'Weekly Trending' but you're assigning latest into it. Same as L48 and L60, L63 and L75.
> 
> https://github.com/xOnlyFadi/h-extensions/blob/55e74ee12b16cabd6c45ce87b61d84175cb41169/src/Koushoku/KoushokuParser.ts#L33-L76

they are like because of paperback homepage style to make 
![2022_05_21_21_05_IMG_6747_V2](https://user-images.githubusercontent.com/63213308/169676599-0f9807d3-4e1a-400a-8be5-b2c594108fcc.png)
![2022_05_21_21_05_IMG_6746_V2](https://user-images.githubusercontent.com/63213308/169676600-650c4665-31e4-44da-894f-f0a2d643da09.png)

**Comment by rs1703** [comment] 2022-05-22 03:30
The screenshots seems mixed to me, Weekly Trending should've been Monthy and vice versa, but if everything is working fine on your end then I guess that's it since I don't know how Paperback works, except maybe this

>https://github.com/xOnlyFadi/h-extensions/blob/55e74ee12b16cabd6c45ce87b61d84175cb41169/src/Koushoku/KoushokuParser.ts#L122

/genres/ should be /tags/.

Thanks, how does Paperback work distribute their extensions? Does it lists all extensions on the app itself or do you have to search and download it manually from the repository? I could say a word and shill the extension on the site or something.

**Comment by xOnlyFadi** [comment] 2022-05-22 03:34
> The screenshots seems mixed to me, Weekly Trending should've been Monthy and vice versa, but if everything is working fine on your end then I guess that's it since I don't know how Paperback works, except maybe this
> 
> > https://github.com/xOnlyFadi/h-extensions/blob/55e74ee12b16cabd6c45ce87b61d84175cb41169/src/Koushoku/KoushokuParser.ts#L122
> 
> /genres/ should be /tags/.
> 
> Thanks, how does Paperback work distribute their extensions? Does it lists all extensions on the app itself or do you have to search and download it manually from the repository? I could say a word and shill the extension on the site or something.

You could see the array loop and how i get the weekly and monthly homepages, and for the genres I forgot to remove the replace function it was used from another source and i forgot to remove it

**Comment by xOnlyFadi** [comment] 2022-05-25 19:29
> The screenshots seems mixed to me, Weekly Trending should've been Monthy and vice versa, but if everything is working fine on your end then I guess that's it since I don't know how Paperback works, except maybe this
> 
> > https://github.com/xOnlyFadi/h-extensions/blob/55e74ee12b16cabd6c45ce87b61d84175cb41169/src/Koushoku/KoushokuParser.ts#L122
> 
> /genres/ should be /tags/.
> 
> Thanks, how does Paperback work distribute their extensions? Does it lists all extensions on the app itself or do you have to search and download it manually from the repository? I could say a word and shill the extension on the site or something.

I just noticed that and I fixed it yesterday and made a push update for it 
https://github.com/xOnlyFadi/h-extensions/blob/main/src/Koushoku/KoushokuParser.ts#L24-L76

**Comment by rs1703** [comment] 2022-05-25 23:40
It's my fault that I didn't explain it clearly, but I'm glad that you noticed it. Once again, I don't know how Paperback distribute their extensions, but if you want to share the extension to the other iPhone users, then just let me know.

And back to the main subject, I'll close this issue since it's related to the browser and there's nothing I could do about it. Thanks.

**Closed by rs1703** 2022-05-25 23:40 UTC
